# Importing numpy:

In [1]:
import numpy as np

# Creating arrays using numpy:

### One dimensional arrays (1D):

In [2]:
food = np.array(["baryani","pasta","chicken rice"])
food

array(['baryani', 'pasta', 'chicken rice'], dtype='<U12')

In [17]:
price = np.array([120,350,630])
price

array([120, 350, 630])

In [4]:
type(food)

numpy.ndarray

In [5]:
type(price)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
len(price)

3

In [8]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [9]:
np.linspace(2,23,num = 8)

array([ 2.,  5.,  8., 11., 14., 17., 20., 23.])

In [10]:
np.empty(5)

array([1.06485147e-311, 6.01346953e-154, 4.47593816e-091, 1.99631762e+161,
       3.98220569e+209])

In [11]:
np.empty(7)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609790e-307,
       1.42410974e-306, 5.28650241e-322, 4.26137297e+257])

In [12]:
np.empty(30,dtype = np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [13]:
np.ones(12,dtype = np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [20]:
bill = np.array([1230,780,560])
total = np.concatenate((price,bill))
total

array([ 120,  350,  630, 1230,  780,  560])

In [22]:
total.sort()
total

array([ 120,  350,  560,  630,  780, 1230])

In [23]:
a = np.array([[1,2,3],[23,4,5]])
a

array([[ 1,  2,  3],
       [23,  4,  5]])

In [30]:
b = np.array([[2,5,6],[1,2,4]])
b

array([[2, 5, 6],
       [1, 2, 4]])

**For concatenation you should keep in mind that axis = 0 is only possible when the number of elements in the 2_D are same in number in both arrays.**

In [31]:
c = np.concatenate((a,b),axis=0)
c

array([[ 1,  2,  3],
       [23,  4,  5],
       [ 2,  5,  6],
       [ 1,  2,  4]])

In [34]:
d = np.array([[7,8,9],
             [3,4,5],
             [1,2,3]])
d

array([[7, 8, 9],
       [3, 4, 5],
       [1, 2, 3]])

In [36]:
d.ndim

2

In [38]:
f = np.array([[[1,2,3],[9,0,7]],[[1,3,4],[8,7,6]],[[9,8,7],[9,7,6]]])
f

array([[[1, 2, 3],
        [9, 0, 7]],

       [[1, 3, 4],
        [8, 7, 6]],

       [[9, 8, 7],
        [9, 7, 6]]])

In [39]:
f.ndim

3

In [41]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
b = np.array([1,2,3,4,45])
b

array([ 1,  2,  3,  4, 45])

In [48]:
b.shape

(5,)

In [53]:
c = b[np.newaxis,:]
c

array([[ 1,  2,  3,  4, 45]])

In [52]:
c = b[:,np.newaxis]
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [45]])